### ISSUE TITLE
Mensagens repetidas para mesma refeição

### ISSUE THREAD

**Issue by arthurcantarela** [Maronato/BandecoAPI#1]
Estou recebendo sempre 2 mensagens por refeição no Telegram

![image](https://user-images.githubusercontent.com/8205796/31177265-dd7e3c26-a8eb-11e7-951d-9d5d9c1938b5.png)

**Comment by Maronato** [comment]
É, eu percebi isso também.
Acho que acontece pq a lambda dá timeout antes de terminar a execução, aí o AWS pensa que tá executando em batch e chama de novo o lambda.

Aumentei aqui o timeout da função e deve resolver. Me avisa se continuar recebendo duplicado
